sudo: required
services:
  - docker

before_install:
  - docker build -t foosi/demo-react-app -f Dockerfile.dev .

script:
  - docker run foosi/demo-react-app npm run test -- --coverage --watchAll=false

