sudo: required
services:
  - docker

before_install:
  - docker build -t foosi/demo-react-app -f Dockerfile.dev .

script:
  - docker run foosi/demo-react-app npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "demo-react-app"
  env: "DemoReactApp-env"
  bucket_name: "elasticbeanstalk-us-west-2-606640617555"
  bucket_path: "demo-react-app"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
